n = input('Digite algo: ')

print(f'O tipo primitivo desse valor é {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'Só contem numeros? {n.isnumeric()}')
print(f'Só contem letras?? {n.isalpha()}')
print(f'Contém letras ou/e números? {n.isalnum()}')
print(f'Está em maiúsculas? {n.isupper()}')
print(f'Está em minúsculas? {n.islower()}')
print(f'Está capitalizada? {n.istitle()}')